env:
  ZUORA_API_ENDPOINT: 'https://rest.apisandbox.zuora.com'

name: zuora workflow デプロイテスト

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Check PR Diff
      - name: check updated filelist
        id: diff_list
        run: gh api /repos/${GITHUB_REPOSITORY}/pulls/${number}/files --jq '.[].filename' >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          number: ${{ github.event.number }}

      # test
      - name: output diff
        run: echo ${{ steps.diff_list.outputs }} 

      # fetch token

      # run import
      - name: run import workflow api
        id: import
        run: |
          TARGET='test'
          VERSION=0.0.1
          DATA=$(cat ./zuora_workflows/${TARGET}/data.json)
          METADATA=$(cat ./zuora_workflows/${TARGET}/data.json)
          curl --location '${ZUORA_API_ENDPOINT}/workflows/import?version=${VERSION}&activate=true' \
          --header 'zuora-version: 239.0' \
          --header 'Content-Type: application/json' \
          --data '${{ DATA }}' >> $GITHUB_OUTPUT
      
      # check result
      - name: check result
        run: |
          echo 
          echo ${{ steps.diff_list.outputs }} 

#        # Updating the workflow ID when registering a new workflow
#       - name: update workflow id
#         uses: jossef/action-set-json-field@v1
#         if: WORKFLOW_ID
#         with:
#           file: zuora_workflows/template/metadata.json
#           field: version
#           value:  ${{ steps.get_current_date_time.outputs.current_date_time }}
